apiVersion: v1
kind: Pod
metadata:
  name: rgaiacs.github.io
spec:
  containers:
  - name: hugo
    image: hugo
    # Used for debug
    # command: ["tail", "-f", "/dev/null"]
    args: ["server", "--buildDrafts"]
    workingDir: /srv/rgaiacs.github.io
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /srv/rgaiacs.github.io
      name: rgaiacs.github.io
  volumes:
  - hostPath:
      path: rgaiacs.github.io
      type: Directory
    name: rgaiacs.github.io