apiVersion: v1
kind: Pod
metadata:
  name: rgaiacs.github.io
spec:
  containers:
  - name: hugo
    image: hugo
    # Used for debug
    # command: ["tail", "-f", "/dev/null"]
    args: ["server", "--bind", "0.0.0.0", "--port", "1313", "--buildDrafts", "--buildFuture", "--watch"]
    workingDir: /srv/rgaiacs.github.io
    ports:
    - containerPort: 1313
      hostPort: 1313
    volumeMounts:
    - mountPath: /srv/rgaiacs.github.io
      name: rgaiacs.github.io
  volumes:
  - hostPath:
      path: rgaiacs.github.io
      type: Directory
    name: rgaiacs.github.io